### ISSUE TITLE
Container link issue

### ISSUE THREAD

**Issue by cgudea** [shivshav/rpi-media-server#9]
need to add links to have name resolved correctly in flexget/sickrage

```
sickrage:
…
    links:
        - transmission
…
```

**Comment by shivshav** [comment]
I can't seem to reproduce this issue from my side. Can you try getting into a bash shell in the sickrage and/or flexget containers and doing
1. `apt-get update && apt-get install iputils-ping`
2. `ping transmission`

when you get a chance and tell me whether that's successful or not? Seems to work from my end, and the test connection button in sickrage's config UI also reports a success.
